import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import React, { useState, useEffect } from 'react'



export default function Home() {

const r = useRouter();

const [showButton, setShowButton] = useState(false);

useEffect(() => {
  setTimeout(() => {
    setShowButton(true);
  }, 4000);
}, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} id="margin">
        <div className={styles.mainContainer} id="sizing">
          <h1>welcome to ●</h1>
          <h2>daily-dictionary</h2>
          {showButton && (
              <button onClick={() => r.push('/words')}>BEGIN</button>
          )}
        </div>
      </main>
    </>
  )
}
