import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import React, { useState, useEffect } from 'react'



export default function Home() {

const r = useRouter();

const [showButton, setShowButton] = useState(false);

useEffect(() => {
  setTimeout(() => {
    setShowButton(true);
  }, 4000);
}, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ddfavicon.ico" />
      </Head>
      <main className={styles.main} id="margin">
        <span className={styles.container} id="main__area">
          <div className={styles.mainContainer}>
            <h1>welcome to ●</h1>
            <h2>daily-dictionary</h2>
            {showButton && (
                <button id="sizing" onClick={() => r.push('/words')}>BEGIN</button>
            )}
          </div>
        </span>
      </main>
    </>
  )
}
